### ISSUE TITLE
Firefox Configuration

### ISSUE THREAD

**Issue by peloeil** [peloeil/nix-config#5]
# TODO
- [x] 情報収集
- [x] デフォルトの検索エンジンを DuckDuckGo にする
- [ ] `home-manager switch --flake .#peloeil` したときに backup の警告が出ないようにする
- [x] 拡張機能を入れる
- [x] multi-account containers
